//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TroveTools.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TroveTools.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*******************************************************************************
        ///Slate Theme for GitHub Pages
        ///by Jason Costello, @jsncostello
        ///*******************************************************************************/
        ///
        ///
        ////*******************************************************************************
        ///MeyerWeb Reset
        ///*******************************************************************************/
        ///
        ///html, body, div, span, applet, object, iframe,
        ///h1, h2, h3, h4, h5, h6, p, blockquote, pre,
        ///a, abb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stylesheet {
            get {
                return ResourceManager.GetString("Stylesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;title&gt;TroveTools.NET: version 1.0.0.3 Beta - Created by Dazo&lt;/title&gt;
        ///&lt;link href=&quot;stylesheet.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=EN-US link=blue vlink=purple&gt;
        ///
        ///    &lt;h2&gt;Coming Soon:&lt;/h2&gt;
        ///    &lt;ul&gt;
        ///        &lt;li&gt;Trovesaurus tab with news, calendar events and contests, server status, mail messages&lt;/li&gt;
        ///        &lt;li&gt;Mod detail pane for selected mod&lt;/li&gt;
        ///    &lt;/ul&gt;
        ///    &lt;h2&gt;Version 1.0.0.3 Beta (6/23/2016)&lt;/h2&gt;
        ///    &lt;ul&gt;
        ///        &lt;li&gt;Settings: run on windows startup option&lt;/li&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VersionHistory {
            get {
                return ResourceManager.GetString("VersionHistory", resourceCulture);
            }
        }
    }
}
