//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TroveTools.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TroveTools.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {
        ///    &quot;id&quot;: &quot;801&quot;,
        ///    &quot;name&quot;: &quot;Neon Rezonance&quot;,
        ///    &quot;author&quot;: &quot;CryoGX&quot;,
        ///    &quot;type&quot;: &quot;WINGS&quot;,
        ///    &quot;subtype&quot;: &quot;&quot;,
        ///    &quot;description&quot;: &quot;&lt;p&gt;Fly around as a true neonic DJ as sound waves flow out of you!&lt;/p&gt;&quot;,
        ///    &quot;date&quot;: &quot;1436058201&quot;,
        ///    &quot;views&quot;: &quot;15637&quot;,
        ///    &quot;status2&quot;: &quot;Work in Progress&quot;,
        ///    &quot;replaces&quot;: &quot;&lt;p&gt;Neophyte Wings&lt;/p&gt;&quot;,
        ///    &quot;totaldownloads&quot;: &quot;7073&quot;,
        ///    &quot;downloads&quot;: [
        ///      {
        ///        &quot;fileid&quot;: &quot;1446&quot;,
        ///        &quot;version&quot;: &quot;X&quot;,
        ///        &quot;date&quot;: &quot;1450555472&quot;,
        ///        &quot;downloads&quot;: &quot;2958&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DesignTimeTroveMod {
            get {
                return ResourceManager.GetString("DesignTimeTroveMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: &quot;6&quot;,
        ///    &quot;name&quot;: &quot;Display No Clouds&quot;,
        ///    &quot;author&quot;: &quot;Ocgineer&quot;,
        ///    &quot;type&quot;: &quot;UTILITY&quot;,
        ///    &quot;subtype&quot;: &quot;&quot;,
        ///    &quot;description&quot;: &quot;&amp;lt;p&amp;gt;This is a simple vfx mod that removes the clouds in the sky.&amp;lt;br /&amp;gt;This would be extremely useful for those that like gliding or build at great heights!&amp;lt;/p&amp;gt;&quot;,
        ///    &quot;date&quot;: &quot;1423870377&quot;,
        ///    &quot;status2&quot;: &quot;Completed&quot;,
        ///    &quot;replaces&quot;: &quot;&quot;,
        ///    &quot;totaldownloads&quot;: 8884,
        ///    &quot;votes&quot;: 7,
        ///    &quot;views&quot;: 12782,
        ///    &quot;downloads&quot;: [
        ///      {
        ///        &quot;f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DesignTimeTroveMods {
            get {
                return ResourceManager.GetString("DesignTimeTroveMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*******************************************************************************
        ///MeyerWeb Reset
        ///*******************************************************************************/
        ///
        ///html, body, div, span, applet, object, iframe,
        ///h1, h2, h3, h4, h5, h6, p, blockquote, pre,
        ///a, abbr, acronym, address, big, cite, code,
        ///del, dfn, img, ins, kbd, q, s, samp,
        ///small, strike, sub, sup, tt, var,
        ///center, dl, dt, dd, ol, ul, li,
        ///b, u, i, em, strong, fieldset, form, label, legend,
        ///table, caption, tbody, tfoot, the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlFieldStylesheet {
            get {
                return ResourceManager.GetString("HtmlFieldStylesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*******************************************************************************
        ///Slate Theme for GitHub Pages
        ///by Jason Costello, @jsncostello
        ///*******************************************************************************/
        ///
        ///
        ////*******************************************************************************
        ///MeyerWeb Reset
        ///*******************************************************************************/
        ///
        ///html, body, div, span, applet, object, iframe,
        ///h1, h2, h3, h4, h5, h6, p, blockquote, pre,
        ///a, abb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stylesheet {
            get {
                return ResourceManager.GetString("Stylesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;main_content_wrap&quot; class=&quot;outer&quot;&gt;&lt;section id=&quot;main_content&quot; class=&quot;inner&quot;&gt;
        ///
        ///## Version 1.0.0.6 Beta (TBD)
        ///- Clicking on the tray icon balloon notification now restores the window in addition to clicking or double-clicking on the tray icon itself
        ///- Trovesaurus tab: sort event calendar by end date, and moved refresh button
        ///- Trovesaurus tab: refresh button now also refreshes mail and server status immediately
        ///- Updated Trovesaurus mail URL
        ///- All tabs with toolbars: hide overflow button (window [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VersionHistory {
            get {
                return ResourceManager.GetString("VersionHistory", resourceCulture);
            }
        }
    }
}
