//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TroveTools.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TroveTools.NET.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AboutViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Formats.
        /// </summary>
        public static string GetMoreModsViewModel_AllFormats {
            get {
                return ResourceManager.GetString("GetMoreModsViewModel_AllFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Subtypes.
        /// </summary>
        public static string GetMoreModsViewModel_AllSubTypes {
            get {
                return ResourceManager.GetString("GetMoreModsViewModel_AllSubTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Types.
        /// </summary>
        public static string GetMoreModsViewModel_AllTypes {
            get {
                return ResourceManager.GetString("GetMoreModsViewModel_AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get More Mods.
        /// </summary>
        public static string GetMoreModsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("GetMoreModsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string MainWindowView_CheckForUpdates {
            get {
                return ResourceManager.GetString("MainWindowView_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TroveTools.NET will continue running in the background while minimized.
        /// </summary>
        public static string MainWindowView_MinimizeBalloonTipText {
            get {
                return ResourceManager.GetString("MainWindowView_MinimizeBalloonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TroveTools.NET.
        /// </summary>
        public static string MainWindowView_MinimizeBalloonTipTitle {
            get {
                return ResourceManager.GetString("MainWindowView_MinimizeBalloonTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open TroveTools.NET.
        /// </summary>
        public static string MainWindowView_OpenTroveTools {
            get {
                return ResourceManager.GetString("MainWindowView_OpenTroveTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit TroveTools.NET.
        /// </summary>
        public static string MainWindowView_QuitTroveTools {
            get {
                return ResourceManager.GetString("MainWindowView_QuitTroveTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TroveTools.NET: version {0} - created by Dazo.
        /// </summary>
        public static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mod component files.
        /// </summary>
        public static string ModderTools_AddFileDialog_Title {
            get {
                return ResourceManager.GetString("ModderTools_AddFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mod YAML file.
        /// </summary>
        public static string ModderTools_OpenYamlDialog_Title {
            get {
                return ResourceManager.GetString("ModderTools_OpenYamlDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mod preview file.
        /// </summary>
        public static string ModderTools_PreviewDialog_Title {
            get {
                return ResourceManager.GetString("ModderTools_PreviewDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save mod YAML file.
        /// </summary>
        public static string ModderTools_SaveYamlDialog_Title {
            get {
                return ResourceManager.GetString("ModderTools_SaveYamlDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modder Tools.
        /// </summary>
        public static string ModderToolsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ModderToolsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trove mod files (*.zip, *.tmod).
        /// </summary>
        public static string MyMods_OpenFileDialog_Filter {
            get {
                return ResourceManager.GetString("MyMods_OpenFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mod files.
        /// </summary>
        public static string MyMods_OpenFileDialog_Title {
            get {
                return ResourceManager.GetString("MyMods_OpenFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Mods.
        /// </summary>
        public static string MyModsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MyModsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trove executable.
        /// </summary>
        public static string Settings_AddLocationDialog_Filter {
            get {
                return ResourceManager.GetString("Settings_AddLocationDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trove location: select Trove.exe file.
        /// </summary>
        public static string Settings_AddLocationDialog_Title {
            get {
                return ResourceManager.GetString("Settings_AddLocationDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("SettingsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name is missing.
        /// </summary>
        public static string TroveLocation_Error_LocationNameMissing {
            get {
                return ResourceManager.GetString("TroveLocation_Error_LocationNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location path is invalid: it does not contain the file Trove.exe.
        /// </summary>
        public static string TroveLocation_Error_LocationPathInvalid {
            get {
                return ResourceManager.GetString("TroveLocation_Error_LocationPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location path is missing.
        /// </summary>
        public static string TroveLocation_Error_LocationPathMissing {
            get {
                return ResourceManager.GetString("TroveLocation_Error_LocationPathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} ({3:N0} downloads, updated {1:d}, file ID {2}).
        /// </summary>
        public static string TroveMod_Download_ToStringFormat {
            get {
                return ResourceManager.GetString("TroveMod_Download_ToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string TroveMod_Status_Downloading {
            get {
                return ResourceManager.GetString("TroveMod_Status_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string TroveMod_Status_Error {
            get {
                return ResourceManager.GetString("TroveMod_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        public static string TroveMod_Status_Installing {
            get {
                return ResourceManager.GetString("TroveMod_Status_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available.
        /// </summary>
        public static string TroveMod_Status_NewVersionAvailable {
            get {
                return ResourceManager.GetString("TroveMod_Status_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up To Date.
        /// </summary>
        public static string TroveMod_Status_UpToDate {
            get {
                return ResourceManager.GetString("TroveMod_Status_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trovesaurus.
        /// </summary>
        public static string TrovesaurusViewModel_DisplayName {
            get {
                return ResourceManager.GetString("TrovesaurusViewModel_DisplayName", resourceCulture);
            }
        }
    }
}
